export const DB_ID = process.env.APPWRITE_DB_ID!

export const COLLECTIONS = {
  USERS: process.env.APPWRITE_COLLECTION_USERS!,
  JOBS: process.env.APPWRITE_COLLECTION_JOBS!,
  APPLICATIONS: process.env.APPWRITE_COLLECTION_APPLICATIONS!,
  INTERVIEWS: process.env.APPWRITE_COLLECTION_INTERVIEWS!,
  TENANTS: process.env.APPWRITE_COLLECTION_TENANTS!,
  AI_CONFIG: process.env.APPWRITE_COLLECTION_AI_CONFIG!,
  TEMPLATES_CONFIG: process.env.APPWRITE_COLLECTION_TEMPLATES_CONFIG!,
  SITE_LAYOUT: process.env.APPWRITE_COLLECTION_SITE_LAYOUT!,
  SCREENINGS: process.env.APPWRITE_COLLECTION_SCREENINGS!,
  LINKEDIN_JOBS: process.env.APPWRITE_COLLECTION_LINKEDIN_JOBS!,
  LINKEDIN_CONFIG: process.env.APPWRITE_COLLECTION_LINKEDIN_CONFIG!,
  LINKEDIN_GROUP_QUEUE: process.env.APPWRITE_COLLECTION_LINKEDIN_GROUP_QUEUE!,
  ANALYTICS_CONFIG: process.env.APPWRITE_COLLECTION_ANALYTICS_CONFIG!,
  VIVIER_CVS: process.env.APPWRITE_COLLECTION_VIVIER_CVS!,
  RECOMMENDATIONS: process.env.APPWRITE_COLLECTION_RECOMMENDATIONS!,
  FUNNEL_STAGES: process.env.APPWRITE_COLLECTION_FUNNEL_STAGES!,
  FUNNEL_EVENTS: process.env.APPWRITE_COLLECTION_FUNNEL_EVENTS!,
  JOB_MATCHES: process.env.APPWRITE_COLLECTION_JOB_MATCHES!,
  APPLICATION_EMAILS: process.env.APPWRITE_COLLECTION_APPLICATION_EMAILS!,
  SUPPORT_TICKETS: process.env.APPWRITE_COLLECTION_SUPPORT_TICKETS!,
  SUPPORT_MESSAGES: process.env.APPWRITE_COLLECTION_SUPPORT_MESSAGES!,
  SOCIAL_POSTS: process.env.APPWRITE_COLLECTION_SOCIAL_POSTS!,
  FUNNEL_PIPELINES: process.env.APPWRITE_COLLECTION_FUNNEL_PIPELINES!,
} as const

export const BUCKETS = {
  CVS: process.env.APPWRITE_STORAGE_CVS!,
  LOGOS: process.env.APPWRITE_STORAGE_LOGOS!,
  RECORDINGS: process.env.APPWRITE_STORAGE_RECORDINGS!,
  VIVIER_CVS: process.env.APPWRITE_STORAGE_VIVIER_CVS!,
  SUPPORT: process.env.APPWRITE_STORAGE_SUPPORT!,
} as const
